### ISSUE TITLE
Sound not playing at all with no error

### ISSUE THREAD

**Issue by TheMemeSniper** [TaylorSMarks/playsound#128]
I am trying to use the playsound module with the following code and filesystem:

```py
playsound.playsound("assets/music/maintheme.mp3",False)
```
```
Development
     Nodebreach - main.py
          assets
               music
                    maintheme.mp3
```
Yet when I execute main.py, no sound plays and no error appears.

I have already installed Gstreamer through apt.

**Comment by tobymac208** [comment]
I am having this issue on my Arch installation. I had to comment out any usage of the playsound module to get the rest of my code working again.

**Comment by TheMemeSniper** [comment]
hm, maybe i should change it to just not playing considering Crostini uses a Debian image

**Comment by liudonghua123** [comment]
Maybe I have a similar issue, I have to wait a few seconds for the sound playing. And I have to add `./` to the path of the sound file.

```
D:\Downloads>python
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from playsound import playsound
>>> playsound("Backstreet Boys - As Long As You Love Me.mid")

    Error 259 for command:
        play "C:\Users\LIUD~1.H\AppData\Local\Temp\PS96ia0aqm.mid" wait
    The driver cannot recognize the specified command parameter.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python311\Lib\site-packages\playsound.py", line 44, in _playsoundWin
    _playsoundWin(tempPath, block)
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python311\Lib\site-packages\playsound.py", line 73, in _playsoundWin
    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python311\Lib\site-packages\playsound.py", line 64, in winCommand
    raise PlaysoundException(exceptionMessage)
playsound.PlaysoundException:
    Error 259 for command:
        play "C:\Users\LIUD~1.H\AppData\Local\Temp\PS96ia0aqm.mid" wait
    The driver cannot recognize the specified command parameter.
>>> playsound("./Backstreet Boys - As Long As You Love Me.mid")
...
>>>
```

**Comment by Mega-Kranus** [comment]
I'm facing the same issue version (1.3.0)

It works perfectly fine on my host OS (Linux Mint) with or without the "block" argument.
It **only fails** to play the sound without an error when the **"blcok" argument is set to False** on my **Windows 10 (VM) on vmware-player.**

I am not sure if this is a VM issue or not. Does anybody know a work around for this issue?
