### ISSUE TITLE
Stops playing sound.  Error 263 for command:

### ISSUE THREAD

**Issue by MoreTore** [TaylorSMarks/playsound#140]
Error 263 for command:
        open speech.mpeg
    The specified device is not open or is not recognized by MCI.

    Error 263 for command:
        close speech.mpeg
    The specified device is not open or is not recognized by MCI.
Failed to close the file: speech.mpeg
Traceback (most recent call last):
  File "D:\Projects\Auto-GPT\scripts\main.py", line 275, in <module>
    prompt = construct_prompt()
  File "D:\Projects\Auto-GPT\scripts\main.py", line 178, in construct_prompt
    config = prompt_user()
  File "D:\Projects\Auto-GPT\scripts\main.py", line 207, in prompt_user
    print_to_console(
  File "D:\Projects\Auto-GPT\scripts\main.py", line 30, in print_to_console
    speak.say_text(f"{title}. {content}")
  File "D:\Projects\Auto-GPT\scripts\speak.py", line 45, in say_text
    success = eleven_labs_speech(text, voice_index)
  File "D:\Projects\Auto-GPT\scripts\speak.py", line 27, in eleven_labs_speech
    playsound("speech.mpeg")
  File "C:\Users\faste\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playsound.py", line 72, in _playsoundWin
    winCommand(u'open {}'.format(sound))
  File "C:\Users\faste\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playsound.py", line 64, in winCommand
    raise PlaysoundException(exceptionMessage)
playsound.PlaysoundException:
    Error 263 for command:
        open speech.mpeg
    The specified device is not open or is not recognized by MCI.

**Comment by MoreTore** [comment]
Solution

pip uninstall playsound
pip install playsound==1.2.2

**Comment by MoreTore** [comment]
https://github.com/Torantulino/Auto-GPT/issues/472
