### ISSUE TITLE
pip install playsound no longer works

### ISSUE THREAD

**Issue by Alexofhtek** [TaylorSMarks/playsound#150]
× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "C:\Users\alexo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\alexo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\alexo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\alexo\AppData\Local\Temp\pip-build-env-7t7l9v70\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\alexo\AppData\Local\Temp\pip-build-env-7t7l9v70\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\alexo\AppData\Local\Temp\pip-build-env-7t7l9v70\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\alexo\AppData\Local\Temp\pip-build-env-7t7l9v70\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "C:\Users\alexo\AppData\Local\Programs\Python\Python312\Lib\inspect.py", line 1282, in getsource
          lines, lnum = getsourcelines(object)
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\alexo\AppData\Local\Programs\Python\Python312\Lib\inspect.py", line 1264, in getsourcelines
          lines, lnum = findsource(object)
                        ^^^^^^^^^^^^^^^^^^
        File "C:\Users\alexo\AppData\Local\Programs\Python\Python312\Lib\inspect.py", line 1093, in findsource
          raise OSError('could not get source code')
      OSError: could not get source code
      [end of output]
  note: This error originates from a subprocess, and is **likely not a problem with pip.**
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is **likely not a problem with pip.**
      
 Here is what i have tried:
pip install --upgrade setuptools
pip install --upgrade wheel
python --m pip install playsound 
python.exe -m pip install --upgrade pip

Also this is not an error with PIP as statedd above in the bolded text

**Comment by Alexofhtek** [comment]
<img width="1260" alt="image" src="https://github.com/TaylorSMarks/playsound/assets/140858473/53e856e9-885d-43ff-aa01-c5e89e58cd70">

**Comment by lundstrj** [comment]
I can confirm this to be a problem also on MacOS with pip 23.3.1 python 3.11

**Comment by MrBreakNFix** [comment]
Also on windows with latest pip & python

**Comment by KartikJain14** [comment]
Can confirm for Windows Python 3.11.7, pip 23.3.1 facing the same issue!

**Comment by KartikJain14** [comment]
`pip install playsound@git+https://github.com/taconi/playsound`
This command can be used temporarily for installing the package tho.

**Comment by 5uperninj4** [comment]
`pip install wheel`
`pip install playsound`
this fixed the issue for me

**Comment by rasmus-ohe** [comment]
> `pip install wheel` `pip install playsound` this fixed the issue for me

Can confirm. This worked for Python 3.11.7, pip 23.3.2

**Comment by nycki93** [comment]
Not working for me on python 3.12.1, pip 23.3.2. I've tried installing wheel first.

**Comment by 5uperninj4** [comment]
> Not working for me on python 3.12.1, pip 23.3.2. I've tried installing wheel first.

Try using python 3.7, many modules don't have support for the newer versions of python
Also, you may come across times you want to use deprecated modules, and python 3.7 still works for a load of them

**Comment by Joshua14Jacob** [comment]
> `pip install wheel` `pip install playsound` this fixed the issue for me

Can confirm, this worked on Python 3.11.1 and pip 24.0

**Comment by Mal-Raven** [comment]
> > `pip install wheel` `pip install playsound` this fixed the issue for me
Though I had to download the playsound package and install it manually, for python 3.10

**Comment by theharshpat** [comment]
> `pip install playsound@git+https://github.com/taconi/playsound` This command can be used temporarily for installing the package tho.

Thanks @taconi @KartikJain14

**Comment by lehcode** [comment]
> `pip install wheel` `pip install playsound` this fixed the issue for me

Worked for me after hours of pain! 

```
RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install setuptools wheel && \
    python3 -m pip install --upgrade setuptools wheel && \
    python3 -m venv .venv && . .venv/bin/activate && \
    pip install -r requirements.txt
```

**Comment by quantumtaoism** [comment]
> `pip install wheel` `pip install playsound` this fixed the issue for me
Installed playsound-1.3.0 eventually with Python 3.11.8 via pip 24.0.
Thank you so much!

**Comment by swolfadder** [comment]
- pip install setuptools wheel
- pip install --upgrade setuptools wheel
- pip install playsound

worked for me on Fedora

**Comment by suraj-rixing** [comment]
> `pip install wheel`

try this if anyone is working on VSCode, it worked for me and I had the same issue.

**Comment by Spacexplorer11** [comment]
> `pip install playsound@git+https://github.com/taconi/playsound` This command can be used temporarily for installing the package tho.

This worked for me

**Comment by aryansenpaii** [comment]
> * pip install setuptools wheel
> * pip install --upgrade setuptools wheel
> * pip install playsound
> 
> worked for me on Fedora

This one Worked for me in version 3.12...Thank you!!!

**Comment by xwzkj** [comment]
> * pip install setuptools wheel
> * pip install --upgrade setuptools wheel
> * pip install playsound
> 
> worked for me on Fedora

It works on python 3.12 ,windows, thanks so much!

**Comment by manualdidact** [comment]
Hoping this issue gets a real fix (installing wheel beforehand is a _workaround_, not a fix). I'm currently working with some applications that happen to require playsound, which cannot be installed with certain tools (eg. poetry, pipx) as they create virtual environments and will not install the wheel package beforehand to accommodate a nonstandard installation issue.

The following steps _must_ work:
```shell
python3 -m venv psvenv
. psvenv/bin/activate
pip install playsound
```

If these steps don't succeed (ie. if playsound can't be installed in a newly created virtualenv), then apps that depend on playsound will fail to install when being handled with common tools that expect standard behavior.

**Comment by jchook** [comment]
Hm, it appears a fix is already submitted for PR. It just needs to be merged. @TaylorSMarks

https://github.com/TaylorSMarks/playsound/pull/146

Or alternatively: https://github.com/TaylorSMarks/playsound/compare/master...taconi:playsound:master

**Comment by manualdidact** [comment]
> Hm, it appears a fix is already submitted for PR. It just needs to be merged. @TaylorSMarks
> 
> #146
> 
> Or alternatively: [master...taconi:playsound:master](https://github.com/TaylorSMarks/playsound/compare/master...taconi:playsound:master)

Can confirm, the following Just Works:
```shell
python3 -m venv psvenv
. psvenv/bin/activate
pip install git+ssh://git@github.com/taconi/playsound.git
```

**Comment by KillerKlown** [comment]
> > Not working for me on python 3.12.1, pip 23.3.2. I've tried installing wheel first.
> 
> Try using python 3.7, many modules don't have support for the newer versions of python Also, you may come across times you want to use deprecated modules, and python 3.7 still works for a load of them

Did anyone get this to work on 3.12 or 3.13 ? I am using the .venv and wheel is installed I think its .045 I uninstalled and reinstalled with latest pycharm playsound still fails. is there a sequence or am I missing a library? I still get the code not found.
Ha!!! nmd I checked the link by manualdidact and I was missing setuptools ....derp.. thx

**Comment by ghost** [comment]
> `pip install playsound@git+https://github.com/taconi/playsound` This command can be used temporarily for installing the package tho.

Don't do this anymore, see [here](https://github.com/TaylorSMarks/playsound/issues/148#issuecomment-3898271743) for other options

**Comment by A-FlemingSantos** [comment]
Apparently, the "playsound" package has been abandoned and is not supported in the latest versions of Python.

An alternative is to use a modified version: `pip install playsound3`
