### ISSUE TITLE
Attempting to use on Rasberry Pi 3: ValueError: Namespace Gst not available

### ISSUE THREAD

**Issue by seanspotatobusiness** [TaylorSMarks/playsound#16]
I have a Rasberry Pi 3 running Raspbian GNU/Linux 9 (stretch).

I get the following error after installing playsound and trying to test following the instructions here: https://pypi.org/project/playsound/

pi@raspberrypi:~/Desktop $ python test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    playsound('./Desktop/DEFCON level change.mp3')
  File "/home/pi/.local/lib/python2.7/site-packages/playsound.py", line 92, in _playsoundNix
    gi.require_version('Gst', '1.0')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available
pi@raspberrypi:~/Desktop $

**Comment by TaylorSMarks** [comment]
I also have a Pi 3 running Raspian. I’d be happy to test and accept any pull requests to fix it.

(I’m not a very good BDFL.)

Taylor

**Comment by omi10859** [comment]
any update i'm still getting the same error?

**Comment by paramda** [comment]
Testing on Raspberry Pi 3 B+ model and have just 2 lines in py code.
Python version 3.5.3

`from playsound import playsound
playsound("alarm.wav")`

I get error mentioned above even after installing packages "gst-make", "gstreamer-player", "fisspy" and "pgi" on Thonny IDE. 
Any help will be truly appreciated. Thanks in advance!

**Comment by paramda** [comment]
@TaylorSMarks , after going through several posts, looks like playsound doesn't work on Debian Linux. Found the below code in link https://raspberrypi.stackexchange.com/questions/7088/playing-audio-files-with-python that does play sound. 
Any timeline for fixing playsound? :) I like the simplicity aspect

**Comment by AvexCodes** [comment]
Any working solutions yet?

I have  a pi 4 and getting the same thing... I really wanna use playsound.

  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/playsound.py", line 92, in _playsoundNix
    gi.require_version('Gst', '1.0')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available

**Comment by vovantamvn** [comment]
I use pi 3 and get wrong

**Comment by gsilvan** [comment]
GStreamer Python bindings are missing. Install them by either:
- **Python 2:** `sudo apt install python-gst-1.0`
- **Python 3:** `sudo apt install python3-gst-1.0`

**Comment by TaylorSMarks** [comment]
If it’s often that easy to fix, it should be made to display a message saying to do so, or it should just automatically take care of it.

Alternatively, can playsound’s linux portion be made to do whatever GStreamer’s Python bindings do, if there’s just some small part needed from it?

**Comment by ar1ja** [comment]
Fixed for me after installing `gst-python`, though now it freezes lmao

**Comment by Lito-Frito** [comment]
> Fixed for me after installing `gst-python`, though now it freezes lmao

Did you ever figure out a fix around the freezing? I tried installing `gst-python` and it didn't fix the sound issue, but now my program freezes haha.

**Comment by yangshengtian** [comment]
> GStreamer Python bindings are missing. Install them by either:
> 
>     * **Python 2:** `sudo apt install python-gst-1.0`
> 
>     * **Python 3:** `sudo apt install python3-gst-1.0`

It seems that, at least for Python 3, we only need to run `sudo apt install gir1.2-gstreamer-1.0`
