### ISSUE TITLE
Error when trying to play a sound, <enum GST_STATE_CHANGE_FAILURE of type Gst.StateChangeReturn>

### ISSUE THREAD

**Issue by SinclairHudson** [TaylorSMarks/playsound#17]
I'm running ubuntu 16.04 off of a USB stick, and I'm getting the following error when I try to play a .wav file.
Traceback (most recent call last):
  File "/media/sinclair/SINCLESTORE/JUNO/labelling.py", line 19, in <module>
    playsound("/SINCLESTORE/JUNO/"+audio_path)
  File "/home/sinclair/.local/lib/python3.5/site-packages/playsound.py", line 106, in _playsoundNix
    "playbin.set_state returned " + repr(set_result))
playsound.PlaysoundException: playbin.set_state returned <enum GST_STATE_CHANGE_FAILURE of type Gst.StateChangeReturn>
not sure what this means. Do I have to change something about my speaker configuration?

Thanks,
Sinclair

**Comment by xPTM1219** [comment]
I know the post is old but, just in case when this error occurred to me it was because the name of the sound was not written correct. Also you could add a try/except and this way the troubleshoot is easier.

**Comment by mwaa123** [comment]
Hi, i have this error ,what can i do?Am trying to put audios in my python file.I am using flask

**Comment by TheTechRobo** [comment]
for me it was that the file didn't exist

**Comment by Ubuntufanboy** [comment]
I know this post is old but I have a solution. You need to remove the ", True" tag at the end of the line. If that doesent work than make sure the file exists with "find" command
