### ISSUE TITLE
Windows 10 error playing with ".ogg" file

### ISSUE THREAD

**Issue by linjiaqin12138** [TaylorSMarks/playsound#37]
```bash
>>> playsound.playsound(os.path.join(os.getcwd(),'bark.ogg'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Program Files\Python37-32\lib\site-packages\playsound.py", line 35, in _playsoundWin
    winCommand('open "' + sound + '" alias', alias)
  File "D:\Program Files\Python37-32\lib\site-packages\playsound.py", line 30, in winCommand
    '\n    ' + errorBuffer.value.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 2: invalid start byte
```

**Comment by TaylorSMarks** [comment]
I'm happy to accept a PR that adds in support for .ogg, so long as it doesn't add in more dependencies, but I don't know of a way of adding that support myself so I'm just going to close the issue.
