### ISSUE TITLE
I Got UnicodeDecodeError because of Turkish characters

### ISSUE THREAD

**Issue by reclinqs** [TaylorSMarks/playsound#62]
PS : _i realised that when i change folder name with non turkish characters it works
"İ" , "Ç" , "ı" characters causes error
_how can i fix this ?__

### **i got this error when using playsound**
Traceback (most recent call last):
  File "C:\folder1\folder2\DERS İÇİN\eklenmeye hazır olanlar\blabla v2.0\blablav2.py", line 34, in <module>
    uEfekt(a)
  File "C:\folder1\folder2\DERS İÇİN\eklenmeye hazır olanlar\blabla v2.0\blablav2.py", line 31, in uEfekt
    playsound(musicFile)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\playsound.py", line 35, in _playsoundWin
    winCommand('open "' + sound + '" alias', alias)
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\site-packages\playsound.py", line 30, in winCommand
    '\n    ' + errorBuffer.value.decode())
**UnicodeDecodeError**: 'utf-8' codec can't decode byte 0xfd in position 24: invalid start byte

**Comment by TaylorSMarks** [comment]
This is now fixed on master. I have added in a test scenario, testBlockingCYRIL_WAV, which should ensure that it doesn't regress.
