### ISSUE TITLE
Not working for python3.8

### ISSUE THREAD

**Issue by Eroc123** [TaylorSMarks/playsound#65]
Due to `platform.linux_distribution` being removed from python3.8 and up, `pip install playsound` has stopped working

when using `pip install playsound`, pip returns the following error
```Traceback (most recent call last):
  File "/home/eric/.local/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/home/eric/.local/lib/python3.8/site-packages/pip/__init__.py", line 217, in main
    return command.main(cmd_args)
  File "/home/eric/.local/lib/python3.8/site-packages/pip/basecommand.py", line 244, in main
    with self._build_session(
  File "/home/eric/.local/lib/python3.8/site-packages/pip/basecommand.py", line 65, in _build_session
    session = PipSession(
  File "/home/eric/.local/lib/python3.8/site-packages/pip/download.py", line 316, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/home/eric/.local/lib/python3.8/site-packages/pip/download.py", line 92, in user_agent
    zip(["name", "version", "id"], platform.linux_distribution()),
AttributeError: module 'platform' has no attribute 'linux_distribution'
```

**Comment by Legion-God** [comment]
Have you tried [fixing your pip?](https://stackoverflow.com/questions/58758447/how-to-fix-module-platform-has-no-attribute-linux-distribution-when-instal)

**Comment by eroc123** [comment]
pip works for other libraries, it's just that in python3.9, some features are removed, causing a few libraries using platform.linux_distribution to break.
