### ISSUE TITLE
Error 275. Cannot find the specified file.  Make sure the path and filename are correct.

### ISSUE THREAD

**Issue by RahulShagri** [TaylorSMarks/playsound#82]
I am running wav and mp3 files on Windows 10 but get this error no matter where the file is kept, inside the folder or outside.

It also throws another error right after that -  `Error 263.  The specified device is not open or is not recognized by MCI.`

**Comment by jeremoquai** [comment]
as well, and would appreciate a solution : was working something like 1 or 2 years ago, and in the meantime I switched to the latest Python version, maybe this is the cause ?

**Comment by jeremoquai** [comment]
>>> playsound('C:\keziah.mp3')

    Error 259 for command:
        play "C:\keziah.mp3" wait
    Le pilote ne peut pas reconnaître le paramètre de commande spécifié.

    Error 305 for command:
        close "C:\keziah.mp3"
    Impossible de spécifier des caractères supplémentaires après une chaîne entre guillemets.
Failed to close the file: "C:\keziah.mp3"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jeremie\AppData\Local\Programs\Python\Python39\lib\site-packages\playsound.py", line 73, in _playsoundWin
    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))
  File "C:\Users\Jeremie\AppData\Local\Programs\Python\Python39\lib\site-packages\playsound.py", line 64, in winCommand
    raise PlaysoundException(exceptionMessage)
playsound.PlaysoundException:
    Error 259 for command:
        play "C:\keziah.mp3" wait
    Le pilote ne peut pas reconnaître le paramètre de commande spécifié.

>>> playsound('C:/keziah.mp3')

    Error 259 for command:
        play C:/keziah.mp3 wait
    Le pilote ne peut pas reconnaître le paramètre de commande spécifié.

    Error 263 for command:
        close C:/keziah.mp3
    Le périphérique spécifié n’est pas ouvert ou n’est pas reconnu par MCI.
Failed to close the file: C:/keziah.mp3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jeremie\AppData\Local\Programs\Python\Python39\lib\site-packages\playsound.py", line 73, in _playsoundWin
    winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))
  File "C:\Users\Jeremie\AppData\Local\Programs\Python\Python39\lib\site-packages\playsound.py", line 64, in winCommand
    raise PlaysoundException(exceptionMessage)
playsound.PlaysoundException:
    Error 259 for command:
        play C:/keziah.mp3 wait
    Le pilote ne peut pas reconnaître le paramètre de commande spécifié.

>>> playsound('C:keziah.mp3')

    Error 263 for command:
        open C:keziah.mp3
    Le périphérique spécifié n’est pas ouvert ou n’est pas reconnu par MCI.

    Error 263 for command:
        close C:keziah.mp3
    Le périphérique spécifié n’est pas ouvert ou n’est pas reconnu par MCI.
Failed to close the file: C:keziah.mp3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jeremie\AppData\Local\Programs\Python\Python39\lib\site-packages\playsound.py", line 72, in _playsoundWin
    winCommand(u'open {}'.format(sound))
  File "C:\Users\Jeremie\AppData\Local\Programs\Python\Python39\lib\site-packages\playsound.py", line 64, in winCommand
    raise PlaysoundException(exceptionMessage)
playsound.PlaysoundException:
    Error 263 for command:
        open C:keziah.mp3
    Le périphérique spécifié n’est pas ouvert ou n’est pas reconnu par MCI.

**Comment by jeremoquai** [comment]
@TaylorSMarks ?

**Comment by TaylorSMarks** [comment]
@jeremoquai - Sorry. There's newer code on master that hasn't been put on pypi yet. Could you try to install the latest version of playsound from github instead of pip and let me know if that works?

If the github version works, I'll try to update what's on pypi this weekend.

**Comment by jeremoquai** [comment]
hi @TaylorSMarks (poke @RahulShagri )
thanks for your kind answer
unfortunately i'm a newbie on Python   ;-)
so I'll wait for the pypi version as I don't know how to install it directly

**Comment by jeremoquai** [comment]
(well i gave it a try and failed : i'm not good at it yet so) @TaylorSMarks please let us know when you update pypi thanks

**Comment by GoldfishGallant** [comment]
I am also having this error. Do I simply have to wait or is there something proactive I can be doing to resolve the issue?

**Comment by HaoHoo** [comment]
I have same issue on Windows 10. Manually close sound file like file.close() before playsound(file) may be can help.

**Comment by juengling** [comment]
It's a long time ago since anything happens here, but I've this error, too. The funny point is: Running `playsound(file_path_name)` in VSCode everything works fine. But packing the application with **pyinstaller** and **InnoSetup**, then installing it to the "user-local" folder on a Windows 11 system with Python 3.12.2, a PlaysoundException occurs.

Log file:
```
Traceback (most recent call last):
  File "contMainwindow.py", line 140, in keypressed # That's my code invoking playsound
  File "playsound.py", line 35, in _playsoundWin
  File "playsound.py", line 31, in winCommand
playsound.PlaysoundException: 
    Error 275 for command:
        open "C:\Users\Christoph Jüngling\AppData\Local\Programs\Catinizer\Katze=cat-meow-14536.mp3" alias playsound_0.2973366339419694
    Die angeforderte Datei wurde nicht gefunden. Stellen Sie sicher, dass Pfad- und Dateiname richtig sind.
```
The last line translated: _"The required file could not be found. Make sure the path and file name is correct."_

And indeed, the given file name and path (mp3 file) **is** correct and existing. Opening it with this path in Windows media plyer works as intended, it says "meeoww" :-)

Do you have any idea to fix that?
