### ISSUE TITLE
OSX Python 3.9, cannot play sound, SyntaxError: invalid syntax, python 3 incompatibility

### ISSUE THREAD

**Issue by ddmee** [TaylorSMarks/playsound#97]
Hi, I tried running `playsound` on osx 11.5.2 with python 3.9

It looks like the import  `from AppKit import NSSound` causes another import that has invalid python 2 syntax. So it looks like you can't run the function on python 3 in osx.

```python
PlaySound.py:22: in test
    playsound(mp3_path)
../../.local/share/virtualenvs/plyanging-FeKuxqpu/lib/python3.9/site-packages/playsound.py:244: in <lambda>
    playsound = lambda sound, block = True: _playsoundAnotherPython('/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python', sound, block, macOS = True)
../../.local/share/virtualenvs/plyanging-FeKuxqpu/lib/python3.9/site-packages/playsound.py:229: in _playsoundAnotherPython
    t.join()
../../.local/share/virtualenvs/plyanging-FeKuxqpu/lib/python3.9/site-packages/playsound.py:218: in join
    raise self.exc
../../.local/share/virtualenvs/plyanging-FeKuxqpu/lib/python3.9/site-packages/playsound.py:211: in run
    self.ret = self._target(*self._args, **self._kwargs)
../../.local/share/virtualenvs/plyanging-FeKuxqpu/lib/python3.9/site-packages/playsound.py:226: in <lambda>
    t = PropogatingThread(target = lambda: check_call([otherPython, playsoundPath, _handlePathOSX(sound) if macOS else sound]))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

popenargs = (['/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python', '/Users/herebo/.local/share/virtualenvs/ply...ers/b0/n6_4ym2j3cn55fzjhnzmtw680000gq/T/pytest-of-herebo/pytest-7/test_play_english_voice0/english_voice_test.mp3'],)
kwargs = {}, retcode = 1
cmd = ['/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python', '/Users/herebo/.local/share/virtualenvs/plya...lders/b0/n6_4ym2j3cn55fzjhnzmtw680000gq/T/pytest-of-herebo/pytest-7/test_play_english_voice0/english_voice_test.mp3']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python', '/Users/herebo/.local/share/virtualenvs/plyanging-FeKuxqpu/lib/python3.9/site-packages/playsound.py', 'file:///private/var/folders/b0/n6_4ym2j3cn55fzjhnzmtw680000gq/T/pytest-of-herebo/pytest-7/test_play_english_voice0/english_voice_test.mp3']' returned non-zero exit status 1.

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py:373: CalledProcessError
-------------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/herebo/.local/share/virtualenvs/plyanging-FeKuxqpu/lib/python3.9/site-packages/playsound.py", line 261, in <module>
    playsound(argv[1])
  File "/Users/herebo/.local/share/virtualenvs/plyanging-FeKuxqpu/lib/python3.9/site-packages/playsound.py", line 119, in _playsoundOSX
    from AppKit import NSSound
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/AppKit/__init__.py", line 8, in <module>
    import objc
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/__init__.py", line 28, in <module>
    from objc._bridgesupport import *
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_bridgesupport.py", line 13, in <module>
    import pkg_resources
  File "/Users/donalmee/.local/share/virtualenvs/plyanging-FeKuxqpu/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1367
    raise SyntaxError(e) from e
                            ^
SyntaxError: invalid syntax
```

**Comment by TaylorSMarks** [comment]
Interesting… Travis CI should have caught that but maybe I had the Mac build disabled since it’s the most expensive one…

That line should be easy enough to rewrite to work on both Python 2 and 3.

**Comment by ddmee** [comment]
I was just having a read at the source and I wondered whether I installed PyObjC would it get around it. 

here https://github.com/TaylorSMarks/playsound/blob/master/playsound.py#L227

**Comment by TaylorSMarks** [comment]
Yes, that should get around the error. 

I want this project to have no hard dependencies, only optional dependencies that can make it run more efficiently.

Taylor

**Comment by ddmee** [comment]
Yeah just tried it and it did get around the error. Which is good enough for me because I don't care about the extra dependency.

The other thing is I'm using `pipenv` to manage my virtualenvs. I don't think that should make a difference to this bug. But I'll mention it just in case.

If you come up with a fix for the no-dependency version, I'll be happy to test it on my osx machine for you.

Thanks for the response,
Donal
